# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78de3142f2990716a7620fb74676730265501883f089dcd8b22d771f8823e251045e3d828c1fe6252ef998fd8b19fbf9dbf243648c14d6257122853a7d333dd

test:
  secret_key_base: e4f6939e05d7a2d9ae06dabc37120dfa10c3e005be1b6fe96ffb0367e3220fbd20193a32f093accd903dbd2c65660caa1e33e7de7fd54726d9c235cabcf92602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
